### ISSUE TITLE
please update to 1.19?

### ISSUE THREAD

**Issue by jacobjake1** [etiaro/mineflayer-antiafk#13]
only works for 1.12.2 which I assume what its intended for, but I need it for 1.19 since 2b2t just updated to 1.19 and I use this as a dependency for one of my projects. Thanks.

**Comment by etiaro** [comment]
Alright, i'll take a look at it.
What projects on 2b2t are you doing? Are they Open Source?
It was created exactly for some 2b2t projects of mine, too, huh
