### ISSUE TITLE
Move head around

### ISSUE THREAD

**Issue by sudofox** [etiaro/mineflayer-antiafk#6]
Any way to make it look around a bit while it's doing its thing?

I'm getting a "Move your head before talking in chat" system message from the server. On my test box its head seems to keep a consistent angle.

**Comment by etiaro** [comment]
There is an action called "rotate". Doesn't it change head position?

**Comment by sudofox** [comment]
Can't check now but does it change both pitch and yaw?
Sorry for closing and reopening, my phone glitched

**Comment by etiaro** [comment]
Yep, look at https://github.com/etiaro/mineflayer-antiafk/blob/master/lib/antiafk.js#L8
